declare const classNames: {
  readonly burger_constructor: "burger_constructor";
  readonly bun_top: "bun_top";
  readonly bun_bottom: "bun_bottom";
  readonly ingredients_container: "ingredients_container";
  readonly ingredient_item: "ingredient_item";
  readonly constructor_button: "constructor_button";
  readonly total_price: "total_price";
  readonly constructor_icon: "constructor_icon";
  readonly error: "error";
  readonly message: "message";
  readonly modal_content: "modal_content";
  readonly checkmark: "checkmark";
  readonly order_section: "order_section";
  readonly price_container: "price_container";
  readonly empty_state: "empty_state";
  readonly empty_bun_placeholder: "empty_bun_placeholder";
  readonly empty_bun_top_placeholder: "empty_bun_top_placeholder";
  readonly empty_bun_bottom_placeholder: "empty_bun_bottom_placeholder";
  readonly empty_ingredients_placeholder: "empty_ingredients_placeholder";
  readonly empty_bun: "empty_bun";
  readonly empty_bun_top: "empty_bun_top";
  readonly empty_bun_bottom: "empty_bun_bottom";
  readonly empty_ingredients: "empty_ingredients";
  readonly hover: "hover";
  readonly ingredient_item_dragging: "ingredient_item_dragging";
};
export default classNames;
